---
name: Create hugomanager release

on:
  push:
    branches: ["main", "master"]
    # Release whenever this file changes
    paths:
      - "src/wp2hugo/cmd/hugomanager/cmd/version.txt"
  workflow_dispatch:

jobs:

  generateTag:

    name: "Auto-generate Git tag whenever version.txt changes"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch git tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/wp2hugo/go.mod
          cache-dependency-path: src/wp2hugo/go.sum

      - name: Read version name
        id: read-version
        run: |
          echo "version=$(cat ./src/wp2hugo/cmd/hugomanager/cmd/version.txt)" > "$GITHUB_OUTPUT"

      - name: Create new tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: "${{ steps.read-version.outputs.version }}-hugomanager"
          tag_prefix: ""
          github_token: ${{ secrets.GITHUB_TOKEN }}

  releaseBinary:

    name: "Release Hugomanager with Go Releaser"
    runs-on: ubuntu-latest
    needs: generateTag
    timeout-minutes: 15
    permissions:
      contents: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: "false"  # We will fetch them explicitly in the next step
          persist-credentials: true

      - name: Fetch git tags
        run: |
          git fetch --force --tags origin 'refs/tags/*-hugomanager:refs/tags/*-hugomanager'
          git tag -d $(git tag -l | grep -v 'hugomanager$')

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          # To prevent cache poisoning
          # Ref: https://woodruffw.github.io/zizmor/audits/#cache-poisoning
          cache: false

      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .hugomanager.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
